// Reads env vars / bindings from the Cloudflare Worker context when deployed
// there, falling back to process.env for local Node dev.
//
// Cloudflare Pages does NOT populate process.env with dashboard-configured
// variables and secrets. Those bindings are only handed to the Worker's
// fetch(request, env, ctx) entry point. Our _worker.js (generated by
// scripts/cf-postbuild.mjs) stashes that `env` object on globalThis so the
// rest of the app — including code bundled deep inside the SSR handler — can
// read secrets (ADMIN_PASSWORD) and bindings (SITE_CONTENT KV) from anywhere.

interface CloudflareEnv {
  [key: string]: unknown;
}

export function getCloudflareEnv(): CloudflareEnv | null {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const env = (globalThis as any).__CF_ENV__;
  return env ?? null;
}

export function getEnvVar(name: string): string | undefined {
  const cfEnv = getCloudflareEnv();
  if (cfEnv && typeof cfEnv[name] === "string") return cfEnv[name] as string;
  return process.env[name];
}
